views and serializers
KrystianOg/PatientRegistrySystem pull request #11
Opened 2022-10-16 13:22 UTC by krasickiPawel

further validation (appointment dates) in next issue

2022-10-16 14:19 UTC, KrystianOg requested changes

2022-10-16 14:19 UTC, KrystianOg commented on api/apps/authentication/models.py
> +        return self.get_type_display()
def type_detail duplicate lines (46-48)

2022-10-16 14:19 UTC, KrystianOg commented on api/apps/core/serializers.py
> +        ]
Check for object permissions & groups instead ->
[django-guardian Group permissions](https://django-guardian.readthedocs.io/en/stable/userguide/assign.html#for-group)

2022-10-16 14:19 UTC, KrystianOg commented on api/apps/core/views.py
> +        return queryset
also Group Permissions

2022-10-16 14:19 UTC, KrystianOg commented on api/apps/core/views.py
> +        return queryset
to samo^

2022-10-18 14:22 UTC, krasickiPawel commented on api/apps/core/serializers.py
> +        ]
racja, to było przed permisjami, teraz już zbędne i wgl słaby kod, poprawię

2022-10-18 20:20 UTC, KrystianOg commented
WARNING!

MERGE AFTER merging #10 and #13

2022-10-19 00:35 UTC, KrystianOg requested changes

2022-10-19 00:35 UTC, KrystianOg commented on api/apps/core/views.py
> +        user_groups = set(user.groups.all().values_list('name', flat=True))
nie musi być .all() gdy jest .values_list()

2022-10-19 00:35 UTC, KrystianOg commented on api/apps/core/views.py
> +        if "Admin" in user_groups or "Doctor" in user_groups:
notka dla większej responsywności bo możemy dodawać więcej grup do listy zamiast pisać kolejne or'y
ale zostaje 
```python
if any(group in ["Admin", "Doctor"] for group in user_groups):
```

2022-10-19 00:35 UTC, KrystianOg commented on api/apps/core/views.py
> +        user_groups = set(user.groups.all().values_list('name', flat=True))
nie musi być .all() gdy jest .values_list()

2022-10-19 01:04 UTC, KrystianOg approved these changes

2022-10-19 01:09 UTC, merged